name: Upgrade Caddy

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 18 * * *"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check if update available
        id: check
        uses: lucacome/docker-image-update-checker@main
        with:
          base-image: caddy:latest
          image: potat0000/caddy:latest
        env:
          DEBUG: ${{ secrets.ACTIONS_STEP_DEBUG }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        if: steps.check.outputs.needs-updating == 'true'
        with:
          username: potat0000
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v3
        if: steps.check.outputs.needs-updating == 'true'
        with:
          push: true
          tags: potat0000/caddy:latest
